version: '2'
services:
  arbitrager:
    build: .
    image: go-arbitrager
    command: go-arbitrager --exchange=huobi,lbank,kucoin
    volumes:
      - ./:/go/src/github.com/fxpgr/go-arbitrager

#    depends_on:
#      - mongo
#    restart: always
#  metabase:
#    image: metabase/metabase
#    environment:
#      MB_DB_TYPE: postgres
#      MB_DB_DBNAME: metabase
#      MB_DB_PORT: 5432
#      MB_DB_USER: postgres
#      MB_DB_PASS: metabase
#      MB_DB_HOST: metabase-db
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mongo
#      - metabase-db
#    restart: always
#  metabase-db:
#    image: postgres:9.6
#    ports:
#      - "5432:5432"
#    volumes:
#      - metabase-db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: metabase
#      POSTGRES_PASSWORD: metabase
#    restart: always


#  mongo:
#    restart: always
#    image: mongo
#    volumes:
#      - mongodb_arbitrager:/data/db
#    ports:
#      - '27017:27017'
#volumes:
#  mongodb_arbitrager:
#  metabase-db:
